Event Hub Track 2 Support (#74)
* Missing application_properties in BatchMessage fixes

* Missing data bytes in BatchMessage fixes

* Updated pylint version

This should resolve Travis error: `AttributeError: 'Import' object has no attribute 'infer_name_module'`

* improve type checking to enable message-like objects in BatchMessage

* pylint error fixes

* remove Python 3.4 from the travis config as Python 3.4 won't be supported from the next release

* Fix memory leak in sending BatchEventData

* improve solution by typecasting NULL to AMQP types

* init commit for websocket support

* Websocket functionality done, but further design is needed

* Reorganzie WebSocket related code

* Remove unnecessary tls http_proxy setting

* Module import and proxy username password update

* Update comment

* Update code

* Fix pylint error

* OAuth support

* Add Message app_prop checking

* Remove scope