Missing application_properties in BatchMessage fixes (#62)
* Missing application_properties in BatchMessage fixes

* Missing data bytes in BatchMessage fixes

* Updated pylint version

This should resolve Travis error: `AttributeError: 'Import' object has no attribute 'infer_name_module'`

* improve type checking to enable message-like objects in BatchMessage

* pylint error fixes

* remove Python 3.4 from the travis config as Python 3.4 won't be supported from the next release